# Generated by Django 3.2.6 on 2021-10-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorturl',
            options={'verbose_name': 'link', 'verbose_name_plural': 'Most viewed links'},
        ),
    ]
