# Generated by Django 3.2.6 on 2021-10-17 13:52

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20211017_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='device',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
