# Generated by Django 3.2.6 on 2021-10-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20211017_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='device',
        ),
    ]
