# Generated by Django 3.2.6 on 2021-10-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_alter_visit_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='device',
        ),
    ]
