# Generated by Django 3.2.6 on 2021-10-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0009_remove_visit_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='device',
            field=models.CharField(blank=True, default='a', max_length=50, null=True),
        ),
    ]
