# Generated by Django 3.2.6 on 2021-10-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0010_visit_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='device',
            field=models.CharField(max_length=50),
        ),
    ]
