# Generated by Django 3.2.6 on 2021-10-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0011_alter_visit_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='device',
            new_name='os',
        ),
    ]
